import { CurrencyPair } from '@/types';

export const CURRENCY_PAIRS: CurrencyPair[] = [
  // Forex пары
  {
    id: 'EURUSD',
    symbol: 'EUR/USD',
    name: 'Euro / US Dollar',
    base: 'EUR',
    quote: 'USD',
    category: 'forex',
  },
  {
    id: 'GBPUSD',
    symbol: 'GBP/USD',
    name: 'British Pound / US Dollar',
    base: 'GBP',
    quote: 'USD',
    category: 'forex',
  },
  {
    id: 'AUDCAD',
    symbol: 'AUD/CAD',
    name: 'Australian Dollar / Canadian Dollar',
    base: 'AUD',
    quote: 'CAD',
    category: 'forex',
  },
  {
    id: 'USDJPY',
    symbol: 'USD/JPY',
    name: 'US Dollar / Japanese Yen',
    base: 'USD',
    quote: 'JPY',
    category: 'forex',
  },
  {
    id: 'USDCAD',
    symbol: 'USD/CAD',
    name: 'US Dollar / Canadian Dollar',
    base: 'USD',
    quote: 'CAD',
    category: 'forex',
  },
  {
    id: 'NZDUSD',
    symbol: 'NZD/USD',
    name: 'New Zealand Dollar / US Dollar',
    base: 'NZD',
    quote: 'USD',
    category: 'forex',
  },
  {
    id: 'EURGBP',
    symbol: 'EUR/GBP',
    name: 'Euro / British Pound',
    base: 'EUR',
    quote: 'GBP',
    category: 'forex',
  },
  {
    id: 'AUDUSD',
    symbol: 'AUD/USD',
    name: 'Australian Dollar / US Dollar',
    base: 'AUD',
    quote: 'USD',
    category: 'forex',
  },
  // Криптовалютные пары
  {
    id: 'BTCUSDT',
    symbol: 'BTC/USDT',
    name: 'Bitcoin / Tether',
    base: 'BTC',
    quote: 'USDT',
    category: 'crypto',
  },
  {
    id: 'ETHUSDT',
    symbol: 'ETH/USDT',
    name: 'Ethereum / Tether',
    base: 'ETH',
    quote: 'USDT',
    category: 'crypto',
  },
  {
    id: 'ADAUSDT',
    symbol: 'ADA/USDT',
    name: 'Cardano / Tether',
    base: 'ADA',
    quote: 'USDT',
    category: 'crypto',
  },
  {
    id: 'DOTUSDT',
    symbol: 'DOT/USDT',
    name: 'Polkadot / Tether',
    base: 'DOT',
    quote: 'USDT',
    category: 'crypto',
  },
  {
    id: 'LINKUSDT',
    symbol: 'LINK/USDT',
    name: 'Chainlink / Tether',
    base: 'LINK',
    quote: 'USDT',
    category: 'crypto',
  },
  {
    id: 'UNIUSDT',
    symbol: 'UNI/USDT',
    name: 'Uniswap / Tether',
    base: 'UNI',
    quote: 'USDT',
    category: 'crypto',
  },
  {
    id: 'AAVEUSDT',
    symbol: 'AAVE/USDT',
    name: 'Aave / Tether',
    base: 'AAVE',
    quote: 'USDT',
    category: 'crypto',
  },
  {
    id: 'SOLUSDT',
    symbol: 'SOL/USDT',
    name: 'Solana / Tether',
    base: 'SOL',
    quote: 'USDT',
    category: 'crypto',
  },
  // OTC пары
  {
    id: 'OTC_EURUSD',
    symbol: 'OTC EUR/USD',
    name: 'OTC Euro / US Dollar',
    base: 'EUR',
    quote: 'USD',
    category: 'otc',
  },
  {
    id: 'OTC_GBPUSD',
    symbol: 'OTC GBP/USD',
    name: 'OTC British Pound / US Dollar',
    base: 'GBP',
    quote: 'USD',
    category: 'otc',
  },
  {
    id: 'OTC_AUDCAD',
    symbol: 'OTC AUD/CAD',
    name: 'OTC Australian Dollar / Canadian Dollar',
    base: 'AUD',
    quote: 'CAD',
    category: 'otc',
  },
  {
    id: 'OTC_USDJPY',
    symbol: 'OTC USD/JPY',
    name: 'OTC US Dollar / Japanese Yen',
    base: 'USD',
    quote: 'JPY',
    category: 'otc',
  },
  {
    id: 'OTC_USDCAD',
    symbol: 'OTC USD/CAD',
    name: 'OTC US Dollar / Canadian Dollar',
    base: 'USD',
    quote: 'CAD',
    category: 'otc',
  },
  {
    id: 'OTC_NZDUSD',
    symbol: 'OTC NZD/USD',
    name: 'OTC New Zealand Dollar / US Dollar',
    base: 'NZD',
    quote: 'USD',
    category: 'otc',
  },
  {
    id: 'OTC_EURGBP',
    symbol: 'OTC EUR/GBP',
    name: 'OTC Euro / British Pound',
    base: 'EUR',
    quote: 'GBP',
    category: 'otc',
  },
  {
    id: 'OTC_AUDUSD',
    symbol: 'OTC AUD/USD',
    name: 'OTC Australian Dollar / US Dollar',
    base: 'AUD',
    quote: 'USD',
    category: 'otc',
  },
];

export const API_ENDPOINTS = {
  COINGECKO: 'https://api.coingecko.com/api/v3',
  BINANCE: 'https://api.binance.com/api/v3',
  ALPHA_VANTAGE: 'https://www.alphavantage.co/query',
  POCKET_OPTION: 'https://api.pocketoption.com/api',
};

export const SOCKET_CONFIG = {
  url: process.env.NODE_ENV === 'production' 
    ? 'https://your-domain.com' 
    : 'http://localhost:3000',
  options: {
    transports: ['websocket'],
    autoConnect: true,
  },
};
